DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS note;

CREATE TABLE "user" (
  id SERIAL NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE note (
  id SERIAL,
  author_id INTEGER NOT NULL,
  root_note_id INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kind INTEGER NOT NULL,
  sentence TEXT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (author_id) REFERENCES "user" (id)
);
